.nycrc, .travis.yml, marko-cli.js, package.json, yarn.lock
=> Integrate Travis CI and Coveralls #1

src/components/ebay-listbox/index.js, src/components/ebay-listbox/test/test.server.js
Fixes #12. Adds test for empty option list.
=> Allow empty listbox

package.json, yarn.lock
Everything looks in order, right Sean?
=> Upgrade to skin 3.4.0

src/components/ebay-button/README.md, src/components/ebay-carousel/README.md, src/components/ebay-menu/README.md, src/components/ebay-notice/README.md, src/components/ebay-select/README.md, src/components/ebay-select/examples/1-basic/template.marko, src/components/ebay-select/examples/2-selected-option/template.marko
Brings all the README documents in sync with one another (re: headings, nomenclature, etc.)
Fixes #34
=> README formatting and text fixes

src/components/ebay-notice/README.md, src/components/ebay-notice/index.js, src/components/ebay-notice/test/test.browser.js
**This is a PR to the Notice PR.**
- moves timeouts
- passes object rather than straight value
- test event data
These are a few changes that I thought would be easier to communicate via PR rather than review.
=> Notice: minor test improvements

CONTRIBUTING.md, scripts/prepublish.js, src/common/transformer/test/test.server.js, src/components/ebay-carousel/test/test.server.js
=> Fixed typos

src/components/ebay-select/index.js, src/components/ebay-select/test/test.browser.js
The 3rd example on marketplace doesn't work
Select UI doesn't change on click and on keyboard when the options are rendered dynamically.
=> convert to string to compare the option array & selected option

demo/browser.json, marko.json, package.json, src/common/transition/index.js, src/common/transition/test/test.browser.js, src/components/ebay-carousel/browser.json, src/components/ebay-dialog/README.md, src/components/ebay-dialog/browser.json, src/components/ebay-dialog/examples/1-basic/template.marko, src/components/ebay-dialog/examples/2-scrolling/template.marko, src/components/ebay-dialog/examples/3-fullscreen/template.marko, src/components/ebay-dialog/examples/4-panel-left/template.marko, src/components/ebay-dialog/examples/5-panel-right/template.marko, src/components/ebay-dialog/examples/6-fill/template.marko, src/components/ebay-dialog/examples/7-focus/template.marko, src/components/ebay-dialog/index.js, src/components/ebay-dialog/template.marko, src/components/ebay-dialog/test/test.browser.js, src/components/ebay-dialog/test/test.server.js, yarn.lock
Adds the `<ebay-dialog>` component mentioned in #6.
<strike>Be sure to `yarn link @ebay/skin` using my branch [here](https://github.com/eBay/skin/tree/6-ebay-dialog).</strike> (now using skin 4 prerelease)
1. There is some weirdness involved in getting the `makeup-js` libraries to work properly with Marko. As you can see in this PR I have setup the widgets lifecycle events to remove any DOM mutations created by makeup before rendering, and then reapplying the mutations after Marko applies it's update.
2. Transitions are automatically enabled based off the type of modal dialog (eg: panel-left slides in from the left).
#6
*Basic Dialog Example*
=> Component: ebay-dialog

README.md, package.json, yarn.lock
- add `@ebay/browserslist-config` devDep
- update internal list
- update docs
https://github.com/eBay/browserslist-config
Closes #97
=> Integrate @ebay/browserslist-config

src/common/event-utils/test/test.browser.js, src/components/ebay-select/README.md, src/components/ebay-select/index.js, src/components/ebay-select/template.marko, src/components/ebay-select/test/test.browser.js, src/components/ebay-select/test/test.server.js
- updated class names to use the Skin's new convention for `combobox`
- fix for a whitespace lint issue in one of the util files 🤷‍♂️
=> Updating styles for the skin change to combobox;

src/components/ebay-dialog/index.js, src/components/ebay-dialog/test/test.server.js
Disables the dialog mask on the fullscreen variant of the dialog.
Related skin pr https://github.com/eBay/skin/pull/196
=> Remove mask from fullscreen dialog.

.browser-refresh-ignore
ignore vscode folder for browser-refresh
=> ignore vscode folder for browser-refresh

demo/browser.json, marko.json, src/components/ebay-radio/README.md, src/components/ebay-radio/browser.json, src/components/ebay-radio/examples/1-default/template.marko, src/components/ebay-radio/examples/2-disabled/template.marko, src/components/ebay-radio/examples/3-grouped-radio/template.marko, src/components/ebay-radio/examples/4-custom-color/template.marko, src/components/ebay-radio/index.js, src/components/ebay-radio/template.marko, src/components/ebay-radio/test/test.browser.js, src/components/ebay-radio/test/test.server.js
ebay-radio component which renders a radio
Issue - #120 
https://dsl.ebay.com/ds6/forms
=> Radio Component

README.md, demo/browser.json, marko.json, src/components/ebay-checkbox/README.md, src/components/ebay-checkbox/browser.json, src/components/ebay-checkbox/examples/1-default/template.marko, src/components/ebay-checkbox/examples/2-disabled/template.marko, src/components/ebay-checkbox/examples/3-grouped-checkbox/template.marko, src/components/ebay-checkbox/examples/4-custom-color/template.marko, src/components/ebay-checkbox/index.js, src/components/ebay-checkbox/template.marko, src/components/ebay-checkbox/test/test.browser.js, src/components/ebay-checkbox/test/test.server.js
ebay-checkbox component which renders a checkbox
Closes #121 
https://dsl.ebay.com/ds6/forms
=> Checkbox Component

README.md
I like badges. I hope you do too :-)
This is intended for master branch.
After this I will do another PR with the Browserstack and Automate text and logo.
=> Readme ci badges

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/PULL_REQUEST_TEMPLATE.md
- create bug and feature issue templates
- minor updates to PR template
These are based off the Marko templates, with a few changes to keep it simple and in similar style to the PR template. Feel free to make changes directly to this branch.
Fixes #193
=> Create github issue templates

README.md
New badge:
Updated Browser Policy section:
=> Added BrowserStack badge & snippet to README

CONTRIBUTING.md
This PR is intended for `master` branch.
Updated the pull requests section of the contributing guide.
The old guidelines did not reflect our actual working model, and some personal preferences. Hopefully these updates are *better* and a little more flexible, but not saying they are perfect either ;-)
https://github.com/eBay/ebayui-core/blob/contributing_updates/CONTRIBUTING.md#pull-requests
=> Docs: updated Pull Request section of contributing guide

package.json, yarn.lock
I released a new version of Marko cli so we can stop relying on the canary release.
=> Update Marko CLI

demo/browser.json, marko.json, src/components/ebay-switch/README.md, src/components/ebay-switch/browser.json, src/components/ebay-switch/examples/01-default/template.marko, src/components/ebay-switch/examples/02-disabled/template.marko, src/components/ebay-switch/examples/03-with-field/template.marko, src/components/ebay-switch/index.js, src/components/ebay-switch/template.marko, src/components/ebay-switch/test/test.browser.js, src/components/ebay-switch/test/test.server.js
- adds new switch component
Overall, code is very similar to the `checkbox` component.
Currently only supports DS4.
Closes #280
=> Switch Component

marko.json, src/components/ebay-switch/README.md
- add `disabled` property to `marko.json`
- fix typo in docs
Broken in apps, but missed this because it worked fine in the local demo. Should look into the difference.
Fixes #329
=> Switch: fix disabled

marketplace.json
Adds the config file for the ui-marketplace.
=> Add ui marketplace config file.

src/components/ebay-switch/template.marko
- adds new classes which are needed for DS6
#342 
https://github.com/eBay/skin/pull/280
DS4:
DS6:
=> Switch: update for DS6

demo/style.less, demo/template.marko
- move navigation to left side
- add design system toggle
The component list is getting long, so easier to navigate from the left. The toggle should help with local debugging now that we need to go back and forth between ds4/ds6 frequently.
=> Demo: update layout

src/components/ebay-pagination/README.md
Update pagination documentation regarding max number of pages.
Fixes https://github.com/eBay/ebayui-core/issues/140
=> Pagination: document max number of pages

package.json, yarn.lock
Updated the makeup-expander dependency to pick up the bugfix.
https://github.com/makeup-js/makeup-expander/pull/7
=> update makeup for touch device fix

README.md, package.json, src/components/ebay-select/index.js, yarn.lock
Rebased changes from master into 1.1.0.  Skin updates and 2 other small changes.
=> 1.1.0 rebase

src/components/ebay-button/README.md
=> Fix backtick in button README

package.json, yarn.lock
Updated dependency and yarn.lock to Skin v6.0.4.
=> Merge 1.0.5 branch into master prior to release

src/common/test-utils/browser.js, src/components/ebay-carousel/index.js, src/components/ebay-carousel/style-touch.less, src/components/ebay-carousel/utils/on-scroll-end/index.js, src/components/ebay-carousel/utils/scroll-transition/index.js
This PR reverts #458.
We have decided to go with a different implementation (which will go out in v2.0.0 instead).
=> Revert PR #458 (Carousel IOS animations)

package.json, src/common/test-utils/browser.js, src/components/ebay-carousel/README.md, src/components/ebay-carousel/index.js, src/components/ebay-carousel/style-touch.less, src/components/ebay-carousel/style.less, src/components/ebay-carousel/template.marko, src/components/ebay-carousel/test/test.browser.js, src/components/ebay-carousel/utils/on-scroll-debounced/index.js, src/components/ebay-carousel/utils/on-scroll-debounced/test/test.browser.js, src/components/ebay-carousel/utils/on-scroll-end/index.js, src/components/ebay-carousel/utils/on-scroll-end/test/test.browser.js, src/components/ebay-carousel/utils/scroll-transition/index.js, src/components/ebay-carousel/utils/scroll-transition/test/test.browser.js, yarn.lock
This should only contain carousel changes and skin update.
=> Merge 1.2.0 branch into master prior to final release.

package.json, src/components/ebay-carousel/index.js, src/components/ebay-carousel/test/test.browser.js
This patch release contains the carousel fix for #488.
DO NOT SQUASH.
=> Merge 1.3.1 branch to master, prior to final release

src/components/ebay-carousel/style.less
This contains the carousel fix only #505
=> Merge 1.3.2 to master prior to release

src/components/ebay-infotip/README.md, src/components/ebay-tooltip/README.md, src/components/ebay-tourtip/README.md
Clearing some low hanging fruit! :-)
=> Tooltip: fixed typo on docs #533

README.md
1. Modified project tagline
1. Added accessibility section under "Principles"
1. Moved "Browser Policy" section under "Principles"
1. Moved "Requirements" section to top and made the fact that this is a Marko project more prominent
=> Docs: added a11y section to readme

src/components/ebay-textbox/examples/06-multiline/template.marko, src/components/ebay-textbox/index.js, src/components/ebay-textbox/template.marko, src/components/ebay-textbox/test/test.server.js
- adds capability to pass a value to a textarea
Fixes #562
=> Allowing textarea to have default value

package.json, src/components/ebay-menu/browser.json, src/components/ebay-menu/index.js, src/components/ebay-menu/template.marko, yarn.lock
Contains two fixes:
* Menu: Shows incorrect data on client side rerender (#564)
* Button: visited link colour for primary fake button should be white (https://github.com/eBay/skin/issues/570)
DO NOT SQUASH.
=> Merge 2.0.5 branch into master prior to final release

package.json, src/components/ebay-textbox/index.js, yarn.lock
- bumps `makeup-floating-label` version for autofill detection
Updates from feedback from users of the component.
Fixes #557
=> Textbox: Floating label fix

package.json, src/components/ebay-button/browser.json, src/components/ebay-button/examples/13-cta/template.marko, src/components/ebay-button/index.js, src/components/ebay-button/template.marko, src/components/ebay-button/test/test.server.js, src/components/ebay-icon/symbols/arrow-right-bold/browser.json, src/components/ebay-icon/symbols/arrow-right-bold/ds4.marko, src/components/ebay-icon/symbols/arrow-right-bold/missing.js
- fixes CTA button variant
- adds `ebay-icon`
- new support for a CTA button in DS4
CTA button variant was not working correctly.
Fixes #568
=> Button: Fixes CTA variant

marko.json, package.json, src/components/ebay-textbox/examples/01-default/template.marko, src/components/ebay-textbox/index.js, src/components/ebay-textbox/template.marko, yarn.lock
- all changes within the 2.0.6 branch, ready for release
**Note:** Only PR changes and version changes should be in this PR.
=> Merge 2.0.6 branch prior to release

src/components/ebay-listbox/template.marko
This is addressing the issue described in #592
=> Listbox: invalid options preservation fix

package.json, src/components/ebay-checkbox/template.marko, src/components/ebay-listbox/template.marko, src/components/ebay-radio/template.marko, yarn.lock
- all changes within the 2.0.7 branch, ready for release
**Note**: Only PR changes and version changes should be in this PR.
=> Merge 2.0.7 branch prior to release

src/components/components/ebay-tooltip-base/index.js, src/components/ebay-icon/template.marko, src/components/ebay-icon/widget.js, src/components/ebay-infotip/template.marko, src/components/ebay-infotip/test/test.browser.js, src/components/ebay-tourtip/test/test.browser.js
All changes within the 2.0.8 branch, ready for release.
- Fix issue with rerendering infotip & tourtip (#602)
- Refactor ebay-icon to keep the DOM more inline with what Marko expects (#603)
**Note:** Only PR changes and version changes should be in this PR.
=> Merge 2.0.8 branch prior to release

package.json, src/components/ebay-button/browser.json, src/components/ebay-button/examples/13-cta/template.marko, src/components/ebay-button/index.js, src/components/ebay-button/template.marko, src/components/ebay-button/test/test.server.js, src/components/ebay-carousel/style-touch.less, src/components/ebay-carousel/style.less, src/components/ebay-icon/symbols/arrow-right-bold/browser.json, src/components/ebay-icon/symbols/arrow-right-bold/ds4.marko, src/components/ebay-icon/symbols/arrow-right-bold/missing.js, yarn.lock
- Button CTA variant; (#574)
- Disable carousel scroll snapping for firefox (#565)
- Bumped Skin version to 7.1.0
**This is a merge commit of previously reviewed code and should not be squashed.**
=> Merge 2.1.0 branch prior to release

src/components/ebay-tourtip/index.js, src/components/ebay-tourtip/template.marko, src/components/ebay-tourtip/test/test.browser.js
Fixes issue where the tourtip could not be closed and adds tests.
Fixes #627
=> Tourtip: Fix regression that prevents the tour tip from closing.

src/components/ebay-combobox/index.js, src/components/ebay-combobox/test/test.server.js
- gets the correct currentValue from the input
Fixes #636
=> Combobox: Fixing initial currentValue

src/common/nodelist-utils/index.js, src/common/nodelist-utils/test/test.browser.js
Now calling `toLowerCase()` on the char that is passed. Also updated tests to check for this.
=> Menu: fix shortcut when CAPS-LOCK enabled

package.json, src/common/nodelist-utils/index.js, src/common/nodelist-utils/test/test.browser.js, src/common/test-utils/browser.js, src/components/ebay-menu/examples/15-icons/template.marko, src/components/ebay-menu/examples/16-sprites/template.marko, src/components/ebay-menu/index.js, src/components/ebay-menu/mock/index.js, src/components/ebay-menu/template.marko, src/components/ebay-menu/test/test.browser.js, yarn.lock
This release only contains the menu filtering feature.
=> Merge 2.3.0 branch to master prior to final release

src/components/ebay-textbox/template.marko
- adds logic check for presence of value
Fixes #696
=> Fix for when multiline is chosen and there is no value;

marko.json, src/components/ebay-select/examples/06-optgroup/template.marko, src/components/ebay-select/index.js, src/components/ebay-select/template.marko
- adds an `<optgroup>` using a matched `optgroup` string
Completes #689
=> Select: add optgroup

src/components/ebay-select/index.js
- changes the optGroups from an array to an object
Fixes #724
=> Select: optgroup option click

src/components/ebay-listbox/index.js
- update host selector for expander
**Note:** this will be directly committed to master, and a new patch version will be released.
Fixes #731
=> Listbox: Fixing expander host selector;

src/components/ebay-infotip/template.marko
=> bug: fix for form submit when clicked on infotip

package.json, src/components/ebay-carousel/template.marko, src/components/ebay-carousel/test/test.browser.js, src/components/ebay-carousel/test/test.server.js, yarn.lock
- updated carousel play/pause class names to playback class
Skin updates.
Related to #733
=> Carousel updates per Skin changes

src/components/ebay-combobox-readonly/index.js, src/components/ebay-combobox-readonly/template.marko, src/components/ebay-combobox-readonly/test/test.server.js, src/components/ebay-combobox/index.js, src/components/ebay-combobox/template.marko, src/components/ebay-combobox/test/test.server.js, src/components/ebay-infotip/template.marko, src/components/ebay-listbox-button/template.marko
Change some styles to get the components to look and render properly
Changed info to be information icon
Changed combobox__options to be combobox__listbox class to match the new one in skin
Changed the listbox span to have listbox__value in order to pick up the styles for selected option
Fixes #810 #814 #809
=> Dropdown bugfixes for 3.0

demo/browser.json, marko.json, src/components/ebay-filter/README.md, src/components/ebay-filter/browser.json, src/components/ebay-filter/examples/01-basic/template.marko, src/components/ebay-filter/examples/02-selected/template.marko, src/components/ebay-filter/examples/03-disabled/template.marko, src/components/ebay-filter/examples/04-truncated/template.marko, src/components/ebay-filter/examples/05-using-fake-buttons/template.marko, src/components/ebay-filter/examples/06-a11y-active-text/template.marko, src/components/ebay-filter/examples/07-html-attributes/template.marko, src/components/ebay-filter/index.js, src/components/ebay-filter/template.marko, src/components/ebay-filter/test/mock/index.js, src/components/ebay-filter/test/test.browser.js, src/components/ebay-filter/test/test.server.js
- adds a new `<ebay-filter>` component
Closes #769 
Related to https://github.com/eBay/skin/issues/701
=> New Component: ebay-filter

src/components/ebay-textbox/README.md, src/components/ebay-textbox/index.js, src/components/ebay-textbox/template.marko, src/components/ebay-textbox/test/test.browser.js
Adding keypress and keyup events to <ebay-textbox> component
=> Adding keypress and keyup events

src/components/ebay-filter-menu/template.marko, src/components/ebay-filter-menu/test/test.browser.js
- test fix for filter-menu when tested in Marko v3
- minor template nit
=> Fix test in Marko v3;

src/components/ebay-tab/index.js, src/components/ebay-tab/test/mock/index.js, src/components/ebay-tab/test/test.browser.js
- fix logical test when `enter` or `spacebar` is pressed
- update tests to catch manual activation
Fixes #887
=> Tabs: Fix manual activation;

src/components/ebay-notice/examples/10-section-notice-overlow-menu/template.marko
Added overflow menu to section notice as example
=> Added section notice overflow example

src/components/ebay-infotip/template.marko
Changed icon simply based on design
#937
=> Changed information-filled icon to information

src/common/transformers/attribute-tags/index.js, src/components/ebay-listbox-button/index.js, src/components/ebay-menu-button/template.marko
Added a fix to support arguments being passed to marko 3 templates. 
Also fixed a lint error (Dunno how that got in there)
`yarn build` passed when I ran locally
=> Fixed arguments issue in marko v3 (and a lint error)

CONTRIBUTING.md, README.md
Ported documentation about deprecation (#352) upstream to 5.0.0
#956
=> Ported documentation about deprecation (#352) upstream to 5.0.0

src/components/ebay-combobox/index.js, src/components/ebay-combobox/test/test.browser.js
- change test for text input and whether the change event should fire on blur
Presently the test tests whether the entered value equals ... the entered value.
Fixes #988
=> Combobox: Fix value change test;

src/components/ebay-checkbox/template.marko, src/components/ebay-checkbox/test/test.server.js
Added support for id on checkbox
Added similar change to how combobox had. 
#992
=> Added id on checkbox for marko 3

package.json, src/components/ebay-combobox/index.js, yarn.lock
Added new option and upgraded makeup active descendant
#1033
=> Updated makeup auto expander for combobox autoscroll

package.json, src/components/ebay-combobox/index.js, yarn.lock
Fixed combobox blur events. On blur will check if the user clicked a menu item, and only then it calls the change event which forces a state change.
Also updated all makeup packages for 4.5.0
#1044
=> Updated combobox change and select events (and updated makeup packages)

marko.json, src/components/ebay-radio/template.marko
Added an id override for marko 3 for ebay-radio
#1049
=> Added id override to radio for marko 3

marko-cli.js
=> Removed windows firefox from CI

src/components/ebay-menu-button/README.md, src/components/ebay-menu-button/component.js, src/components/ebay-menu-button/marko-tag.json
This is the same fix as #1065 but for `5.x.x` branch
#1058
=> Added an option collapseOnSelect to close menu on option selection

src/components/ebay-icon/widget.js
Fixed an issue with icon serialization for marko 3
=>  Fixed an issue with JSON serialization 

src/components/ebay-icon/component-browser.js
Fixed an issue with icon serialization for marko 4
PR for marko v3 related to this is https://github.com/eBay/ebayui-core/pull/1094
=> Fixed an issue with JSON serialization

src/components/ebay-details/README.md, src/components/ebay-details/examples/05-multiple-options/template.marko, src/components/ebay-details/examples/05-rtl/template.marko, src/components/ebay-details/examples/06-multiple-options/template.marko, src/components/ebay-details/index.marko, src/components/ebay-details/marko-tag.json, src/components/ebay-details/test/test.server.js
Removed RTL attribute, users can add `dir="rtl"` as needed for this. 
For #1090
=> Removed RTL attribute on details

src/components/ebay-menu-button/component.js, src/components/ebay-menu-button/test/test.browser.js, src/components/ebay-textbox/component.js, src/components/ebay-textbox/index.marko, src/components/ebay-textbox/test/test.browser.js
Added focus shortcut for component
Added tests for focus using hidden marko methods. 
#1004
#1081
=> Added focus methods for menu and textbox

.travis.yml, package.json, src/components/components/ebay-tooltip-base/index.js, src/components/ebay-carousel/index.js, yarn.lock
This is the same PR as #1139 but ported to `4.5.0`.
Also fixed Travis CI to use node 10
=> Added focusables to triger after request Animation and fixed travis CI

src/components/ebay-combobox/README.md, src/components/ebay-combobox/component.js, src/components/ebay-combobox/examples/08-sticky-option/template.marko, src/components/ebay-combobox/marko-tag.json
Added option for combobox to have a sticky option.
Added a modifier to be sticky which is ignored in the filter list. Documented it and added an example
#1116
=> Added sticky option to combobox

src/components/ebay-combobox/component.js, src/components/ebay-combobox/examples/08-actionable-button/template.marko, src/components/ebay-combobox/examples/09-actionable-button/template.marko, src/components/ebay-combobox/index.marko, src/components/ebay-combobox/marko-tag.json, src/components/ebay-combobox/style.js, src/components/ebay-combobox/test/mock/index.js, src/components/ebay-combobox/test/test.browser.js, src/components/ebay-combobox/test/test.server.js
* Added actionable icon to combobox. Also added an example for it. 
One of the issue was that when clicking the icon, it would trigger a close since the focus left the input. I changed it so it will not close when button is clicked
#1099
Note, there is a skin issue (which is also present in skin) where the button looks off. Will need a skin change too.
=> Added combobox actionable icon

src/components/ebay-combobox/README.md, src/components/ebay-combobox/index.marko
Added aria-roledescription. It will take user input first, and then it will default to english text (and change based on autocomplete value)
#1151
=> Added aria-roledescription to combobox

README.md, src/components/ebay-icon/index.marko, src/components/ebay-textbox/index.marko
Fixed several issues:
* Added check for multiline in textbox to now show type
* Added extra check for null on lassoConfig (Should fallback to DS6)
* Added info about skin in readme.
#1156 
#1030
#1134
=> Bugfixes for 5.6

src/components/ebay-notice/README.md, src/components/ebay-notice/examples/13-page-notice-no-icon/template.marko, src/components/ebay-notice/index.marko, src/components/ebay-notice/marko-tag.json, src/components/ebay-notice/test/mock/index.js, src/components/ebay-notice/test/test.server.js
Addresses the issue described here: https://github.com/eBay/ebayui-core/issues/1086
=> add explicit option to hide icon in notice

src/components/ebay-menu-button/README.md, src/components/ebay-menu-button/examples/20-fake-disabled/template.marko, src/components/ebay-menu/README.md, src/components/ebay-menu/index.marko
Added disabled version of menu item.
I had initially thought about adding a disabled attribute. However, part of it is also tied to the href so I made fake links always disable on no href. I also added a disabled attribute but did not expose it.
ebay/skin#1154
=> Menu disabled

package.json, src/components/ebay-menu-button/index.marko, src/components/ebay-menu-button/marko-tag.json, yarn.lock
Added `textAlign="center"` for menu-button. 
Also upgraded skin to add support for it
=> Added menu-button center option

src/components/ebay-textbox/examples/20-floating-fluid/template.marko, src/components/ebay-textbox/index.marko
Fixes https://github.com/eBay/skin/issues/1193
=> Changed floating tag to be div instead of span in fluid case

src/components/components/ebay-dialog-base/index.marko, src/components/ebay-combobox/index.marko, src/components/ebay-stepper/index.marko, src/components/ebay-toast/index.marko
Just renamed consts to vars
Did it for every index.marko to not break any other tests.
#1182
=> Changed const to var in marko files

README.md
=> Regenerated browserstack key for readme

src/components/ebay-stepper/README.md, src/components/ebay-stepper/examples/06-center-current/template.marko, src/components/ebay-stepper/examples/07-all-complete/template.marko, src/components/ebay-stepper/index.marko
Added confirmation type. 
#1189
=> Stepper confirmation

src/components/ebay-dialog/examples/06-fill/template.marko, src/components/ebay-dialog/index.marko
=> Fixed dialog close button to be on the right for lightbox

src/components/ebay-icon/component-browser.js
Changed icon wrapper to be a hidden div which has an svg inside it.
#1225
=> Added hidden div wrapper to Icons

src/components/components/ebay-dialog-base/index.marko, src/components/ebay-fullscreen-dialog/README.md, src/components/ebay-lightbox-dialog/README.md, src/components/ebay-panel-dialog/README.md, src/components/ebay-panel-dialog/examples/03-custom-button/template.marko, src/components/ebay-panel-dialog/marko-tag.json
Also updated dialog readmes with `@attribute-tags`
#1223
=> Added custom dialog close 

src/components/components/ebay-dialog-base/index.marko, src/components/components/ebay-dialog-base/test/test.browser.js, src/components/components/ebay-tooltip-overlay/index.marko, src/components/ebay-button/style.js, src/components/ebay-combobox/style.js, src/components/ebay-filter-menu/index.marko, src/components/ebay-infotip/style.js, src/components/ebay-textbox/style.js, src/components/ebay-tooltip/style.js, src/components/ebay-tourtip/style.js
* Changed all actionables to icon-button
* Updated `icon-btn` in some places like dialog close and infotip
* Changed filter-menu `status` to be `checkbox`
* Had to fix some dialog tests since there are two classes, was failing on assertion (checking if it has class of: "`icon-btn lightbox-dialog__close`", basically would fail on space). I added a iteration instead
=> Synced ebayui with skin changes

package.json, src/components/ebay-infotip/README.md, src/components/ebay-infotip/component.js, src/components/ebay-infotip/examples/05-infotip-modal/template.marko, src/components/ebay-infotip/index.marko, src/components/ebay-infotip/marko-tag.json, src/components/ebay-infotip/migrator.js, src/components/ebay-infotip/test/mock/index.js, src/components/ebay-infotip/test/test.server.js, yarn.lock
Changed infotip modal boolean trap to be just variant.
Forced newer version of highlight to load so it fixes node 12 issue. 
(#1147)
=> Fixed node 12 to work and changed modal boolean

package.json, src/components/ebay-listbox-button/template.marko, yarn.lock
Also updated chromedriver
#1171
=> Removed w-preserve-attr=class from listbox 

src/components/ebay-listbox-button/index.marko, src/components/ebay-listbox/index.marko
Same as #1242 but for `5.x` branch
#1171
=> Removed no update from listbox class

src/components/ebay-button/style.js
Added link to button depdenencies
#1244
=> Added link to button depdency for style

src/components/ebay-combobox/README.md, src/components/ebay-combobox/component.js, src/components/ebay-combobox/examples/11-floating-label/template.marko, src/components/ebay-combobox/index.marko, src/components/ebay-combobox/marko-tag.json, src/components/ebay-combobox/style.js, src/components/ebay-combobox/test/mock/index.js, src/components/ebay-combobox/test/test.browser.js
Added floating label to work with combobox
#1273
=> Added floating label to combobox

src/components/ebay-expand-button/README.md, src/components/ebay-fake-tabs/README.md, src/components/ebay-notice/migrator.js, src/components/ebay-panel-dialog/README.md, src/components/ebay-section-notice/README.md, src/components/ebay-tabs/README.md
Fixes for `6.0.0`
* Updated readme
* Fixed typo in migrator
#1282 #1283
=> 6.0 bugfixes

src/components/components/ebay-dialog-base/index.marko
Added ignore-escape attribute 
Did not document it, kept it as hidden for now
=> Added ignoreEscape attribute (Backport from #1203)

src/components/ebay-combobox/component.js, src/components/ebay-combobox/examples/11-readonly/template.marko, yarn.lock
=> Combobox: small fix to support readonly story (#1291)

src/components/ebay-textbox/README.md, src/components/ebay-textbox/component-browser.js, src/components/ebay-textbox/index.marko, src/components/ebay-textbox/test/test.browser.js
Added `onInvalid` textbox event and forward method
#1294
=> Added invalid textbox event

src/components/ebay-icon/icons/ebay-breadcrumb-icon/symbol.js
Reimported skin breadcrumb icons
https://github.com/eBay/skin/issues/1352
=> Updated breadcrumb icon to match skin

README.md, src/components/ebay-progress-bar/README.md, src/components/ebay-progress-bar/component.js, src/components/ebay-progress-bar/examples/01-empty/template.marko, src/components/ebay-progress-bar/examples/02-half/template.marko, src/components/ebay-progress-bar/examples/03-full/template.marko, src/components/ebay-progress-bar/examples/04-custom-min-max/template.marko, src/components/ebay-progress-bar/index.marko, src/components/ebay-progress-bar/marko-tag.json, src/components/ebay-progress-bar/style.js
This PR adds the Progress Bar component to ebay-ui. I included a several examples. 
closes #1267
=> Added Progress Bar Component to Ebay-UI

README.md, src/components/ebay-eek/README.md, src/components/ebay-eek/browser.json, src/components/ebay-eek/eek-util.js, src/components/ebay-eek/examples/01-A+++/template.marko, src/components/ebay-eek/examples/02-A++/template.marko, src/components/ebay-eek/examples/03-A+/template.marko, src/components/ebay-eek/examples/04-A/template.marko, src/components/ebay-eek/examples/05-invalid-combinations/template.marko, src/components/ebay-eek/index.marko, src/components/ebay-eek/marko-tag.json, src/components/ebay-eek/style.js, src/components/ebay-eek/test/test.server.js, src/components/ebay-icon/icons/ebay-eek-arrow-icon/browser.json, src/components/ebay-icon/icons/ebay-eek-arrow-icon/index.marko, src/components/ebay-icon/icons/ebay-eek-arrow-icon/marko-tag.json, src/components/ebay-icon/icons/ebay-eek-arrow-icon/symbol.js, src/components/ebay-icon/icons/ebay-eek-arrow-icon/symbol[ds-4].js, src/components/ebay-icon/icons/ebay-eek-range-arrow-icon/browser.json, src/components/ebay-icon/icons/ebay-eek-range-arrow-icon/index.marko, src/components/ebay-icon/icons/ebay-eek-range-arrow-icon/marko-tag.json, src/components/ebay-icon/icons/ebay-eek-range-arrow-icon/symbol.js, src/components/ebay-icon/icons/ebay-eek-range-arrow-icon/symbol[ds-4].js
Added new eek component. Imported icons from skin
https://github.com/eBay/ebayui-core/issues/1340
=> feat(eek): added new eek component

src/components/ebay-carousel/component.js, src/components/ebay-carousel/marko-tag.json, src/components/ebay-carousel/test/test.server.js
Added the option `hidden-scrollbar` to add the right skin class
Also added some tests
https://github.com/eBay/skin/issues/1431
=> feat(carousel): added hidden scrollbar option

src/components/ebay-badge/README.md
Adds type to the badge README.
closes #1390
=> chore: add type to badge README

src/components/components/ebay-notice-base/index.marko, src/components/components/ebay-notice-base/test/test.server.js, src/components/ebay-inline-notice/index.marko, src/components/ebay-inline-notice/test/test.server.js
This PR removes aria-labelledby from inline-notice
closes #1394
=> Removed aria-labelledby from inline-notice

src/components/components/ebay-dialog-base/index.marko, src/components/ebay-alert-dialog/index.marko, src/components/ebay-confirm-dialog/index.marko, src/components/ebay-drawer-dialog/index.marko, src/components/ebay-icon/index.marko
Added some attributes to ignore list for dialog-base.
Initially I had added them in individual components, but they were causing issues with tests.
Also rearranged the input so that they get replaced correctly.
#1402
=> fix(dialog-base): added attributes to ignoreAttributes list

scripts/generate-cdn.js, src/components/ebay-video/README.md, src/components/ebay-video/component.js, src/components/ebay-video/elements.js, src/components/ebay-video/examples/10-actions/template.marko, src/components/ebay-video/index.marko, src/components/ebay-video/loader.js, src/components/ebay-video/marko-tag.json, src/components/ebay-video/style.less, src/components/ebay-video/versions.json
Updated some things with video
* Added report button to overflow for now
* Added programatic play/pause button
* Misc cleanup, deployed a new version with ui/css shaka player controls.
=> Video controls

src/components/ebay-video/README.md, src/components/ebay-video/component.js, src/components/ebay-video/elements.js, src/components/ebay-video/marko-tag.json
* Changed report button to focus on overflow menu after cliking
* Added text override for report button
=> fix(video): added focus when clicking report, and text input

src/components/ebay-carousel/component.js, src/components/ebay-carousel/marko-tag.json
Added hidden option `no-peek` to hide peek on carousel
=> feat(carousel): added hidden option to hide peek

src/components/ebay-pagination/README.md, src/components/ebay-pagination/component.js, src/components/ebay-pagination/examples/06-buttons-interactive/template.marko, src/components/ebay-pagination/index.marko
Added index to event arguments
https://github.com/eBay/ebayui-core/issues/1407
=> fix(pagination): added index to select event

src/components/ebay-tooltip/component-browser.js, src/components/ebay-tooltip/examples/01-icon-button-host/template.marko, src/components/ebay-tooltip/examples/02-anchor-host/template.marko, src/components/ebay-tooltip/examples/03-pointer-location/template.marko, src/components/ebay-tooltip/examples/04-pointer-with-custom-location/template.marko, src/components/ebay-tooltip/examples/05-no-hover/template.marko, src/components/ebay-tooltip/index.marko
For some reason, tooltip was missing a component-browser.js
I added one and removed the class component from examples to see that it is working properly.
=> fix(tooltip): added component-browser for client side events

package-lock.json, package.json, src/components/ebay-video/component.js, src/components/ebay-video/index.marko, src/components/ebay-video/versions.json
There was a problem with video tag and marko rerenders which would cause it unusable and not working. In this case, forced video tag to not rerender.
=> fix(video): changed video tag to not update based on marko rerenders

src/components/ebay-video/index.marko
Typo in ebay-video - should be track not tack
=> fix(video): tack to track

src/components/ebay-video/component.js, src/components/ebay-video/index.marko
* Fixed a bug with marko 5 and no-update
* Fixed ios controls to not show on pause (https://github.com/eBay/ebayui-core/issues/1445)
* Fixed container size (also on skin) (https://github.com/eBay/ebayui-core/issues/1447)
=> fix(video): fixed ios controls, marko 5 bug, and ios overlay

src/components/ebay-carousel/component.js, src/components/ebay-carousel/index.marko, src/components/ebay-carousel/marko-tag.json
Added key to carousel items
https://github.com/eBay/ebayui-core/issues/1448
=> fix(carousel): added key to items

src/components/ebay-combobox/README.md
=> Combobox: added focus event to readme

.storybook/main.js, src/components/ebay-confirm-dialog/confirm-dialog.stories.js, src/components/ebay-confirm-dialog/examples/01-default/template.marko, src/components/ebay-details/README.md, src/components/ebay-drawer-dialog/README.md, src/components/ebay-drawer-dialog/drawer-dialog.stories.js, src/components/ebay-drawer-dialog/examples/01-default/template.marko, src/components/ebay-fake-menu-button/examples/09-icon-with-text/template.marko, src/components/ebay-fake-menu-button/fake-menu-button.stories.js, src/components/ebay-fake-menu/fake-menu.stories.js, src/components/ebay-filter-menu-button/filter-menu-button.stories.js, src/components/ebay-filter-menu/filter-menu.stories.js, src/components/ebay-filter/filter.stories.js, src/components/ebay-fullscreen-dialog/examples/01-basic/template.marko, src/components/ebay-fullscreen-dialog/fullsceen-dialog.stories.js, src/components/ebay-lightbox-dialog/examples/01-basic/template.marko, src/components/ebay-lightbox-dialog/lightbox-dialog.stories.js, src/components/ebay-listbox-button/listbox-button.stories.js, src/components/ebay-listbox/listbox.stories.js, src/components/ebay-menu-button/menu-button.stories.js, src/components/ebay-menu/menu.stories.js, src/components/ebay-panel-dialog/examples/01-basic/template.marko, src/components/ebay-panel-dialog/panel-dialog.stories.js, src/components/ebay-snackbar-dialog/examples/01-basic/template.marko, src/components/ebay-snackbar-dialog/index.marko, src/components/ebay-snackbar-dialog/snackbar-dialog.stories.js, src/components/ebay-toast-dialog/examples/01-default/template.marko, src/components/ebay-toast-dialog/toast-dialog.stories.js
Added actions tabs. Added actions for most stories. 
https://github.com/eBay/ebayui-core/issues/1494
=> feat: addeed storybook actions

.storybook/storybook-code-source/index.js, src/components/ebay-alert-dialog/alertDialog.stories.js, src/components/ebay-badge/badge.stories.js, src/components/ebay-breadcrumbs/breadcrumbs.stories.js, src/components/ebay-button/button.stories.js, src/components/ebay-carousel/carousel.stories.js, src/components/ebay-checkbox/checkbox.stories.js, src/components/ebay-combobox-readonly/combobox-readonly.stories.js, src/components/ebay-combobox/combobox.stories.js, src/components/ebay-cta-button/cta-button.stories.js, src/components/ebay-details/details.stories.js, src/components/ebay-fake-menu-button/fake-menu-button.stories.js, src/components/ebay-fake-menu/fake-menu.stories.js, src/components/ebay-fake-tabs/fake-tabs.stories.js, src/components/ebay-filter-menu/filter-menu.stories.js, src/components/ebay-infotip/infotip.stories.js, src/components/ebay-listbox-button/listbox-button.stories.js, src/components/ebay-menu/menu.stories.js, src/components/ebay-pagination/pagination.stories.js, src/components/ebay-radio/radio.stories.js, src/components/ebay-select/select.stories.js, src/components/ebay-switch/switch.stories.js, src/components/ebay-tabs/tabs.stories.js, src/components/ebay-textbox/textbox.stories.js, src/components/ebay-toast-dialog/toast-dialog.stories.js, src/components/ebay-tourtip/component-browser.js, src/components/ebay-tourtip/index.marko, src/components/ebay-tourtip/tourtip.stories.js, src/components/ebay-tri-state-checkbox/tri-state-checkbox.stories.js, src/components/ebay-video/video.stories.js
* Finished adding all events
* Added tagsToString fixes for non reprated attribute tags
* Added tagsToString for some most components
* Added `text` doc
* Added `spread` attribute to button (just for a sample of how it should be, if it's good then will add to all components.)
https://github.com/eBay/ebayui-core/issues/1494
=> fea(storybook): documentation additions

src/components/ebay-carousel/carousel.stories.js, src/components/ebay-confirm-dialog/confirm-dialog.stories.js, src/components/ebay-drawer-dialog/drawer-dialog.stories.js, src/components/ebay-eek/eek.stories.js, src/components/ebay-expand-button/expand-button.stories.js, src/components/ebay-fake-link/fake-link.stories.js, src/components/ebay-fullscreen-dialog/fullsceen-dialog.stories.js, src/components/ebay-lightbox-dialog/lightbox-dialog.stories.js, src/components/ebay-program-badge/program-badge.stories.js, src/components/ebay-progress-bar/progress-bar.stories.js, src/components/ebay-progress-spinner/progress-spinner.stories.js, src/components/ebay-progress-stepper/progress-stepper.stories.js, src/components/ebay-section-notice/section-notice.stories.js, src/components/ebay-section-title/section-title.stories.js, src/components/ebay-select/select.stories.js, src/components/ebay-signal/signal.stories.js, src/components/ebay-snackbar-dialog/snackbar-dialog.stories.js, src/components/ebay-tabs/tabs.stories.js, src/components/ebay-textbox/textbox.stories.js, src/components/ebay-tooltip/tooltip.stories.js, src/components/ebay-window-notice/window-notice.stories.js
* Finished all the storybook examples
https://github.com/eBay/ebayui-core/issues/1494
=> feat(storybook): added code examples for all stories

package-lock.json, package.json, src/components/ebay-menu-button/README.md, src/components/ebay-menu-button/component.js
Added `originalEvent` to `change events on menu-button
https://github.com/eBay/ebayui-core/issues/1527
=> feat(menu-button): added original event to change

src/components/ebay-tri-state-checkbox/component.js, src/components/ebay-tri-state-checkbox/index.marko, src/components/ebay-tri-state-checkbox/test/test.browser.js
Added keydown even to tristate checkbox, like we have in ebay-checkbox
https://github.com/eBay/ebayui-core/issues/1576
=> feat(tri-state-checkbox): added keydown event

src/components/ebay-inline-notice/inline-notice.stories.js, src/components/ebay-page-notice/page-notice.stories.js, src/components/ebay-section-notice/section-notice.stories.js, src/components/ebay-window-notice/window-notice.stories.js
Changed notice to show "attention" as a11yText
#1544
=> fix(notice): removed see this notice message (#1544)

src/components/ebay-listbox-button/index.marko, src/components/ebay-listbox-button/listbox-button.stories.js, src/components/ebay-listbox-button/marko-tag.json, src/components/ebay-listbox-button/test/test.server.js
Added floating-label support to listbox
#1519
=> feat(listbox-button): added floating-label support

src/components/ebay-section-title/index.marko, src/components/ebay-section-title/section-title.stories.js, src/components/ebay-section-title/test/mock/index.js, src/components/ebay-section-title/test/test.server.js
Updated section-title to match EVO changes
#1567
=> feat(section-title): updated section-title to match EVO

.github/workflows/node.js.yml
~~testing~~
Ready to merge!
Fix was to add ssh private keys support. The keys were added into the secrets
https://github.com/eBay/ebayui-core/issues/1623
=> fix(actions): fixed github actions to pass

src/components/ebay-fake-link/index.marko
Changed fake-link to not be dynamic. Seems like it was a copy pand paste issue
https://github.com/eBay/ebayui-core/issues/1618
=> fix(fake-link): removed dynamic tag

marko-cli.js, package-lock.json, package.json, src/components/ebay-button/button.stories.js, src/components/ebay-button/index.marko, src/components/ebay-menu-button/index.marko, src/components/ebay-menu-button/marko-tag.json, src/components/ebay-menu-button/menu-button.stories.js, src/components/ebay-split-button/README.md, src/components/ebay-split-button/browser.json, src/components/ebay-split-button/component.js, src/components/ebay-split-button/examples/basic.marko, src/components/ebay-split-button/examples/radio-menu.marko, src/components/ebay-split-button/index.marko, src/components/ebay-split-button/marko-tag.json, src/components/ebay-split-button/split-button.stories.js, src/components/ebay-split-button/style.js, src/components/ebay-split-button/test/__snapshots__/renders-button-with-priority-delete.expected.html, src/components/ebay-split-button/test/__snapshots__/renders-button-with-priority-primary.expected.html, src/components/ebay-split-button/test/__snapshots__/renders-button-with-priority-secondary.expected.html, src/components/ebay-split-button/test/__snapshots__/renders-button-with-size-large.expected.html, src/components/ebay-split-button/test/__snapshots__/renders-defaults.expected.html, src/components/ebay-split-button/test/__snapshots__/renders-loading-state.expected.html, src/components/ebay-split-button/test/__snapshots__/renders-various-options.expected.html, src/components/ebay-split-button/test/__snapshots__/renders-with-menu-items.expected.html, src/components/ebay-split-button/test/mock/index.js, src/components/ebay-split-button/test/test.browser.js, src/components/ebay-split-button/test/test.server.js
Closes #1606
__NOTE__ This is required to make it look properly: https://github.com/eBay/skin/issues/1690 Please apply the fixes from that bug when testing. 
* Added split button new component
* Used snapshot for testing
* Added links to readme to storybook and examples
https://github.com/eBay/ebayui-core/issues/1606
=> feat(split-button): added new component

src/components/ebay-filter-menu/component.js
Added method to reset index for teams to call
https://github.com/eBay/ebayui-core/issues/1629
=> feat(filter-menu): added reset index method

src/components/ebay-button/button.stories.js, src/components/ebay-button/index.marko, src/components/ebay-button/marko-tag.json, src/components/ebay-menu-button/index.marko, src/components/ebay-menu-button/menu-button.stories.js, src/components/ebay-menu-button/test/__snapshots__/renders-with-borderless-true.expected.html
We missed adding borderless support for button last version. 
Added it here and updated menu button to support the new button borderless argument
=> feat: added borderless to button (sync from skin)

src/components/ebay-icon/examples/all.marko, src/components/ebay-icon/icons/ebay-stepper-current-icon/index.marko, src/components/ebay-icon/icons/ebay-stepper-current-icon/marko-tag.json, src/components/ebay-icon/icons/ebay-stepper-current-icon/symbol.js, src/components/ebay-progress-stepper/index.marko, src/components/ebay-progress-stepper/test/__snapshots__/renders-blocked-progress-stepper.expected.html, src/components/ebay-progress-stepper/test/__snapshots__/renders-default-state-progress-stepper.expected.html, src/components/ebay-progress-stepper/test/__snapshots__/renders-default-without-pragraph.expected.html, src/components/ebay-progress-stepper/test/__snapshots__/renders-in-old-progress-progress-stepper-remove-next-version.expected.html, src/components/ebay-progress-stepper/test/__snapshots__/renders-in-progress-progress-stepper.expected.html, src/components/ebay-progress-stepper/test/__snapshots__/renders-vertical-progress-stepper.expected.html, src/components/ebay-progress-stepper/test/test.server.js
* Added defaultState=current as an option.
* Did not add documentation. This is a hidden option. I added it manually to test it. This will be documented only in release notes.
https://github.com/eBay/ebayui-core/issues/1750
=> feat(progress-stepper): added defaultState=current for backwards comp

src/components/ebay-combobox/component.js
Fixes: 
- #1771 JS error because expander did not exist
- #1782 multiple options selected on keyboard input
=> fix(combobox): #1771 JS error because expander did not exist and #1782 multiple options selected on keyboard input

src/components/components/ebay-notice-base/index.marko, src/components/ebay-section-notice/component.js, src/components/ebay-section-notice/examples/with-dismiss.marko, src/components/ebay-section-notice/index.marko, src/components/ebay-section-notice/marko-tag.json, src/components/ebay-section-notice/section-notice.stories.js
* Updated section notice to have dismissed state
* Mostly reused code from `page-notice`
https://github.com/eBay/skin/issues/1883
=> feat(section-notice): added dismiss

src/components/ebay-listbox-button/index.marko, src/components/ebay-listbox-button/listbox-button.stories.js, src/components/ebay-listbox-button/test/__snapshots__/renders-with-floating-label.expected.html
=> fix(listbox-button): do not render unselected text with floating label

src/components/ebay-checkbox/checkbox.stories.js, src/components/ebay-fake-menu-button/fake-menu-button.stories.js, src/components/ebay-fake-menu/fake-menu.stories.js
Updated the storybook documentation to sync with current code implementation.
#1889, #1892, #1891
=> docs(checkbox, fake-menu, fake-menu-button): synced docs with code

src/components/ebay-avatar/README.md, src/components/ebay-avatar/avatar.stories.js, src/components/ebay-avatar/browser.json, src/components/ebay-avatar/examples/custom-body.marko, src/components/ebay-avatar/examples/default.marko, src/components/ebay-avatar/examples/image.marko, src/components/ebay-avatar/examples/signedout.marko, src/components/ebay-avatar/index.marko, src/components/ebay-avatar/marko-tag.json, src/components/ebay-avatar/style.js, src/components/ebay-avatar/test/__snapshots__/renders-128-px-with-magenta.expected.html, src/components/ebay-avatar/test/__snapshots__/renders-defaults.expected.html, src/components/ebay-avatar/test/__snapshots__/renders-signed-out.expected.html, src/components/ebay-avatar/test/__snapshots__/renders-with-custom-body.expected.html, src/components/ebay-avatar/test/__snapshots__/renders-with-doggy-as-username.expected.html, src/components/ebay-avatar/test/__snapshots__/renders-with-image.expected.html, src/components/ebay-avatar/test/__snapshots__/renders-with-robert-as-username.expected.html, src/components/ebay-avatar/test/__snapshots__/renders-with-test-as-usernames.expected.html, src/components/ebay-avatar/test/test.server.js, src/components/ebay-avatar/util.js, src/components/ebay-icon/examples/all.marko, src/components/ebay-icon/icons/ebay-avatar-signed-out-icon/index.marko, src/components/ebay-icon/icons/ebay-avatar-signed-out-icon/marko-tag.json, src/components/ebay-icon/icons/ebay-avatar-signed-out-icon/symbol.js
Added avatar module
https://github.com/eBay/ebayui-core/issues/1896
=> feat(avatar): new module

src/components/ebay-date-textbox/component.js
Added a type guard against document for date textbox during server rendering.
The document object is not accessible from the server side.
=> fix(date-textbox): add guard against document for server side

src/components/ebay-avatar/test/__snapshots__/renders-with-robert-as-username.expected.html, src/components/ebay-avatar/util.js
* Added `Math.abs` to avatar to change the number to be positive. 
https://github.com/eBay/ebayui-core/issues/1935
=> fix(avatar): added Math.abs to get a positive number

src/components/ebay-date-textbox/index.marko
- Fixes #1952 
This ended up being based on an embarrassingly simple mistake 🙈. Quick one-line fix.
=> fix(date-textbox): properly handle textbox changes based on index

src/components/ebay-video/component.js, src/components/ebay-video/elements.js, src/components/ebay-video/index.marko, src/components/ebay-video/video.stories.js
* As per marko team changed video tag to import icons from template (load the icons in the template and then clone them to use them in other places)
* Added all shaka events to video. 
https://github.com/eBay/ebayui-core/issues/1960
https://github.com/eBay/ebayui-core/issues/1962
=> fix(video): added all shaka events and moved icons to be in template

src/components/ebay-pagination/examples/a11y-text.marko, src/components/ebay-pagination/examples/arrows-disabled.marko, src/components/ebay-pagination/examples/basic-links.marko, src/components/ebay-pagination/examples/buttons-interactive.marko, src/components/ebay-pagination/examples/buttons.marko, src/components/ebay-pagination/examples/hidden-pages.marko, src/components/ebay-pagination/examples/no-arrows.marko, src/components/ebay-radio/examples/custom-color.marko, src/components/ebay-radio/examples/default.marko, src/components/ebay-radio/examples/disabled-with-label.marko, src/components/ebay-radio/examples/grouped-radio.marko, src/components/ebay-radio/examples/with-label.marko, src/components/ebay-switch/examples/default.marko, src/components/ebay-switch/examples/disabled-with-label.marko, src/components/ebay-switch/examples/with-label.marko, src/components/ebay-textbox/examples/both-icons.marko, src/components/ebay-textbox/examples/external-label-disabled.marko, src/components/ebay-textbox/examples/external-label.marko, src/components/ebay-textbox/examples/floating-label-autocomplete.marko, src/components/ebay-textbox/examples/floating-label.marko, src/components/ebay-textbox/examples/postfix-icon.marko, src/components/ebay-textbox/examples/prefix-icon.marko, src/components/ebay-textbox/textbox.stories.js
* Added all events to storybook templates that had been missing them. 
#1931 
#1932 
#1933 
#1934
=> chore(storybook): exposed events

src/components/ebay-lightbox-dialog/component.js, src/components/ebay-lightbox-dialog/examples/default.marko, src/components/ebay-lightbox-dialog/examples/focus.marko, src/components/ebay-lightbox-dialog/examples/scrolling.marko, src/components/ebay-lightbox-dialog/examples/with-footer.marko, src/components/ebay-lightbox-dialog/examples/with-prev-button.marko, src/components/ebay-lightbox-dialog/index.marko, src/components/ebay-lightbox-dialog/lightbox-dialog.stories.js, src/components/ebay-lightbox-dialog/test/__snapshots__/renders-basic-version.expected.html, src/components/ebay-lightbox-dialog/test/__snapshots__/renders-expressive-version.expected.html, src/components/ebay-lightbox-dialog/test/__snapshots__/renders-in-open-state.expected.html, src/components/ebay-lightbox-dialog/test/__snapshots__/renders-scrolling-dialog.expected.html, src/components/ebay-lightbox-dialog/test/__snapshots__/renders-size-narrow.expected.html, src/components/ebay-lightbox-dialog/test/__snapshots__/renders-size-wide.expected.html, src/components/ebay-lightbox-dialog/test/__snapshots__/renders-with-header-and-footer.expected.html, src/components/ebay-lightbox-dialog/test/__snapshots__/renders-with-previous-button.expected.html, src/components/ebay-lightbox-dialog/test/test.browser.js
* Added changes from skin to ebayui for lightbox dialog
* Reused most of the code from drawer dialog for this
https://github.com/eBay/ebayui-core/issues/1974
=> feat(lightbox-dialog): added popover variant

src/components/ebay-button/index.marko, src/components/ebay-button/test/__snapshots__/renders-expanded-button-migrator.expected.html, src/components/ebay-button/test/__snapshots__/renders-expanded-button.expected.html
=> fix(button): use 16px icon for expand body-state

src/components/ebay-chip/test/__snapshots__/renders-interactive-close-button-when-label-is-provided.expected.html, src/components/ebay-chip/test/__snapshots__/renders-static-default.expected.html, src/components/ebay-drawer-dialog/README.md, src/components/ebay-infotip/index.marko, src/components/ebay-infotip/test/__snapshots__/renders-default.expected.html
* swapped drawer dialog with lightbox
* I also restructured the infotip and dialog. If we placed dialog inside of infotip, the styles were messing with the close button. So I moved it out (like skin has it)
* Added a deprecated to drawer dialog
https://github.com/eBay/ebayui-core/issues/1998
(Also resolved this issue)
https://github.com/eBay/ebayui-core/issues/1949
=> feat(infotip): swapped to lightbox and layout

src/components/ebay-breadcrumbs/component.js
=> fix(breadcrumbs): use the right target

src/components/ebay-calendar/component.js, src/components/ebay-calendar/index.marko
Months were being shifted on the first day of the month in CET timezone, an additional UTC cast fixed the issue.
=> fix(calendar): timezone bug

package-lock.json, package.json, scripts/prepublish.js, src/components/ebay-button/component-browser.ts, src/components/ebay-button/constants.ts, src/components/ebay-button/index.marko, src/components/ebay-carousel/index.marko, src/components/ebay-lightbox-dialog/component.ts, src/components/ebay-lightbox-dialog/index.marko, src/components/ebay-menu-button/component.ts, src/components/ebay-split-button/component.ts, tsconfig.json
* Fixed an issue with exports from typescript. 
* Refactored some input code to allow `export =`
=> fix: typescript bug with exporting files

src/components/ebay-avatar/avatar.stories.ts, src/components/ebay-avatar/util.ts
Added new pink color to avatar
#2058
=> feat(avatar): added new color

src/components/components/ebay-notice-base/component.ts, src/components/ebay-checkbox/component-browser.ts, src/components/ebay-tabs/component.ts
- Fixes #2065 
- Resolved various typescript issues
=> fix(checkbox, tabs, notice): typescript issues

src/components/ebay-confirm-dialog/index.marko, src/components/ebay-toggle-button-group/component.ts
- Fixes #2064 
- Modify event handler types
=> fix(confirm-dialog): event handler types

src/components/ebay-chips-combobox/chips-combobox.stories.ts, src/components/ebay-chips-combobox/component.ts, src/components/ebay-chips-combobox/examples/attr-tags.marko, src/components/ebay-chips-combobox/examples/default.marko, src/components/ebay-chips-combobox/index.marko, src/components/ebay-chips-combobox/marko-tag.json
- Refactor to allow _either_ a list input or a list of attr tags
=> refactor(chips-combobox): use attr tags for options

src/components/components/ebay-dialog-base/component.ts, src/components/components/ebay-tooltip-base/component-browser.ts
=> fix(tooltip): use declare for type

src/components/ebay-area-chart/area-chart.stories-ignore.ts, src/components/ebay-area-chart/component.ts, src/components/ebay-bar-chart/bar-chart.stories-ignore.ts, src/components/ebay-bar-chart/component.ts, src/components/ebay-line-chart/component.ts, src/components/ebay-line-chart/line-chart.stories.ts
- Fixes #2038 
- Use `import type` instead of `import` for Highcharts
- Fix broken `maxVal` code
=> fix(highcharts): fix types

src/components/ebay-menu-button/menu-button.stories.ts, src/components/ebay-menu-button/test/test.server.js
* Fixed an issue with label documentation
#2023
=> docs(menu-button): added more info about prefix label

marko.json, src/components/ebay-skeleton/marko.json, tsconfig.json
- Fixes #2089 
- Change tsconfig target to ES2015
- Add skeleton components to taglib
=> fix: change tsconfig target & add skeleton taglib

CONTRIBUTING.md
Updated contributing to include info about changesets.
=> chore: updated contributing to include changeset

.changeset/quiet-drinks-worry.md, src/components/ebay-tourtip/component.ts
=> fix(tourtip): fix host type

.changeset/nice-islands-visit.md, src/components/ebay-icon-button/component-browser.ts, src/components/ebay-icon-button/icon-button.stories.ts, src/components/ebay-icon-button/index.marko, src/components/ebay-icon-button/test/__snapshots__/Renders-defaults.expected.txt, src/components/ebay-icon-button/test/__snapshots__/renders-badged-icon-variant.expected.txt, src/components/ebay-icon-button/test/__snapshots__/renders-button-with-priority-delete.expected.txt, src/components/ebay-icon-button/test/__snapshots__/renders-button-with-priority-primary.expected.txt, src/components/ebay-icon-button/test/__snapshots__/renders-button-with-priority-secondary.expected.txt, src/components/ebay-icon-button/test/__snapshots__/renders-button-with-size-large.expected.txt, src/components/ebay-icon-button/test/__snapshots__/renders-button-with-size-small.expected.txt, src/components/ebay-icon-button/test/__snapshots__/renders-disabled-version.expected.txt, src/components/ebay-icon-button/test/__snapshots__/renders-fake-version.expected.txt, src/components/ebay-icon-button/test/__snapshots__/renders-icon.expected.txt, src/components/ebay-icon-button/test/__snapshots__/renders-partially-disabled-version.expected.txt, src/components/ebay-icon-button/test/test.browser.js, src/components/ebay-icon-button/test/test.server.js
* Added priority to icon button
* Updated tests to use storybook and snapshots
https://github.com/eBay/ebayui-core/issues/2155
=> feat(icon-button): added priority

.changeset/lazy-lamps-boil.md, src/components/ebay-date-textbox/component.ts
- Include more information for `invalid-date` event
=> feat(date-textbox): include information for invalid-date event

.changeset/lazy-oranges-serve.md, src/components/ebay-icon-button/icon-button.stories.ts, src/components/ebay-icon-button/test/__snapshots__/Renders-defaults.expected.txt, src/components/ebay-icon-button/test/__snapshots__/renders-button-with-priority-delete.expected.txt, src/components/ebay-icon-button/test/__snapshots__/renders-button-with-priority-primary.expected.txt, src/components/ebay-icon-button/test/__snapshots__/renders-button-with-priority-secondary.expected.txt, src/components/ebay-icon-button/test/__snapshots__/renders-button-with-size-large.expected.txt, src/components/ebay-icon-button/test/__snapshots__/renders-button-with-size-small.expected.txt, src/components/ebay-icon-button/test/__snapshots__/renders-disabled-version.expected.txt, src/components/ebay-icon-button/test/__snapshots__/renders-partially-disabled-version.expected.txt
* Added `aria-label` as name to storybook and changed it to camel case. 
https://github.com/eBay/ebayui-core/issues/2190
=> docs(icon-button): fixed aria-label support

.changeset/good-dolphins-approve.md, src/components/ebay-toggle-button/component.ts
- Resolves #2247 
- Attr tag types need the `Marko.AttrTag` helper
=> fix(toggle-button): attr tag types

.changeset/giant-comics-arrive.md, src/common/mask/index.ts
~~* Note * this requires https://github.com/eBay/ebayui-core/pull/2253 to be merged first to see the changes here~~
* Updated phone input to use the latest masking code to work on safari
https://github.com/eBay/ebayui-core/issues/2231
=> fix(phone-input): updated masking logic for safari

.changeset/healthy-starfishes-joke.md, src/components/ebay-listbox-button/marko-tag.json, src/components/ebay-textbox/marko-tag.json
Updated marko-jsons with missing attributes 
https://github.com/eBay/ebayui-core/issues/2260
=> fix(listbox/textbox): updated marko-jsons

src/global.d.ts
fix the ts error when `import code from "./example/example.marko?raw"`
=> fix(typescript): error for raw marko import

.changeset/green-fans-occur.md, src/components/ebay-table/README.md, src/components/ebay-table/browser.json, src/components/ebay-table/component.ts, src/components/ebay-table/examples/data.json, src/components/ebay-table/examples/default.marko, src/components/ebay-table/index.marko, src/components/ebay-table/marko-tag.json, src/components/ebay-table/style.ts, src/components/ebay-table/table.stories.ts, src/components/ebay-table/test/__snapshots__/test.server.js.snap, src/components/ebay-table/test/test.server.js
https://github.com/eBay/ebayui-core/issues/2234
=> feat(ebay-table): ebay-table base component with density attribute

.changeset/eighty-icons-buy.md, src/components/ebay-table/component.ts, src/components/ebay-table/examples/data.json, src/components/ebay-table/examples/with-actions.marko, src/components/ebay-table/index.marko, src/components/ebay-table/marko-tag.json, src/components/ebay-table/table.stories.ts, src/components/ebay-table/test/__snapshots__/test.server.js.snap
Supporting columnType `layout` (flex display) and `icon-action` (centered with fixed width).
=> feat(ebay-table): table with actions

README.md, src/components/ebay-list/README.md, src/components/ebay-list/browser.json, src/components/ebay-list/component-browser.ts, src/components/ebay-list/examples/interactive.marko, src/components/ebay-list/examples/static.marko, src/components/ebay-list/examples/with-separator.marko, src/components/ebay-list/index.marko, src/components/ebay-list/list.stories.ts, src/components/ebay-list/marko-tag.json, src/components/ebay-list/style.ts, src/components/ebay-list/test/__snapshots__/test.server.js.snap, src/components/ebay-list/test/test.server.js
* List ebayui component
* Used `as` to determine the list item type
* For the click event, I only emit it on button
https://github.com/eBay/ebayui-core/issues/2225
=> feat(list): new component

.changeset/polite-cats-rest.md, src/components/ebay-table/component.ts, src/components/ebay-table/examples/sort-client-side.marko, src/components/ebay-table/examples/sort-with-link.marko, src/components/ebay-table/examples/sort.marko, src/components/ebay-table/index.marko, src/components/ebay-table/table.stories.ts, src/components/ebay-table/test/__snapshots__/test.server.js.snap, src/components/ebay-table/test/sort/test.browser.js
https://github.com/user-attachments/assets/f57d8a50-bf51-4e0c-9103-5d2a9deb244c
=> feat(ebay-table): support column sorting

.changeset/sixty-bananas-kick.md, src/components/ebay-ccd/README.md, src/components/ebay-ccd/browser.json, src/components/ebay-ccd/ccd.stories.ts, src/components/ebay-ccd/examples/default.marko, src/components/ebay-ccd/examples/withCharger.marko, src/components/ebay-ccd/examples/withChargerAndUSBPD.marko, src/components/ebay-ccd/examples/withUSBPD.marko, src/components/ebay-ccd/examples/withoutCharger.marko, src/components/ebay-ccd/index.marko, src/components/ebay-ccd/marko-tag.json, src/components/ebay-ccd/style.ts, src/components/ebay-ccd/test/__snapshots__/test.server.js.snap, src/components/ebay-ccd/test/test.server.js, src/components/ebay-icon/icons/ebay-ccd-charger-included-icon/index.marko, src/components/ebay-icon/icons/ebay-ccd-charger-included-icon/marko-tag.json, src/components/ebay-icon/icons/ebay-ccd-charger-included-icon/symbol.ts, src/components/ebay-icon/icons/ebay-ccd-charger-not-included-icon/index.marko, src/components/ebay-icon/icons/ebay-ccd-charger-not-included-icon/marko-tag.json, src/components/ebay-icon/icons/ebay-ccd-charger-not-included-icon/symbol.ts, src/components/ebay-icon/icons/ebay-ccd-top-icon/index.marko, src/components/ebay-icon/icons/ebay-ccd-top-icon/marko-tag.json, src/components/ebay-icon/icons/ebay-ccd-top-icon/symbol.ts
* Added CCD component
* We need to toggle between one and two figures in this. Added some boolean types to allow toggling
https://github.com/eBay/ebayui-core/issues/2326
=> feat(ccd): added new component
